# Generated by Django 3.0.8 on 2020-08-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donar_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donar_name', models.CharField(max_length=50)),
                ('time_ago', models.CharField(max_length=10)),
                ('donate_amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Endorsement_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_pro_pic', models.CharField(max_length=70)),
                ('end_name', models.CharField(max_length=50)),
                ('end_status', models.CharField(max_length=10)),
                ('end_comment', models.TextField()),
            ],
        ),
    ]
